### ISSUE TITLE
arsalan - There's a risk of underflow

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#107]
arsalan

medium

# There's a risk of underflow

## Vulnerability Detail
in the AsyncSynthVault file and in the decreaseDepositRequest function when subtracting assets from epochs[epochId].depositRequestBalance[owner]. If the balance is less than assets, it will result in an underflow, leading to unexpected behavior and potentially allowing the user to withdraw more assets than they have deposited.

## Impact
potentially allowing the user to withdraw more assets than they have deposited.

## Code Snippet

        `    function decreaseDepositRequest(uint256 assets)
        external
        whenClosed
        whenNotPaused
    {
        address owner = _msgSender();
        uint256 oldBalance = epochs[epochId].depositRequestBalance[owner];
        epochs[epochId].depositRequestBalance[owner] -= assets;
        _asset.safeTransferFrom(address(pendingSilo), owner, assets);

        emit DecreaseDepositRequest(
            epochId,
            owner,
            oldBalance,
            epochs[epochId].depositRequestBalance[owner]
        );
      `
## Tool used

Manual Review

## Recommendation
To prevent underflow, you should add a check to ensure that the balance is sufficient before subtracting assets.

**Comment by blablalf** [comment]
If the balance is less than assets, it will result in an underflow, leading to a revert.
