### ISSUE TITLE
0xKartikgiri00 - `AsyncSynthVault::_claimRedeem` function is using the standard `transfer` function may not be able to retrieve tokens.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#118]
0xKartikgiri00

medium

# `AsyncSynthVault::_claimRedeem` function is using the standard `transfer` function may not be able to retrieve tokens.

## Summary
In `AsyncSynthVault::_claimRedeem` function is using the standard `IERC20.transfer()` function, If asset token is like USDT, it will not be able to transfer out, because this kind of token does not return bool this will cause it to always revert.

## Vulnerability Detail
As per contest readme states:-
"Which ERC20 tokens do you expect will interact with the smart contracts?
weth, usdc, usdt, wbtc"

The issue here is with the use of unsafe transfer() function. The ERC20.transfer() function return a boolean value indicating success. This parameter needs to be checked for success. Some tokens do not revert if the transfer failed but return false instead.

Some tokens (like USDT) don't correctly implement the EIP20 standard and their transfer() function return void instead of a success boolean. Calling these functions with the correct EIP20 function signatures will always revert.

Tokens that don't actually perform the transfer and return false are still counted as a correct transfer and tokens that don't correctly implement the latest EIP20 spec, like USDT, will be unusable in the protocol as they revert the transaction because of the missing return value.

In `VaultZapper` contract  `withdrawToken` function is calling `safeTransfer` function but `AsyncSynthVault::_claimRedeem` function is not calling `safeTransfer`.

For example:
In`AsyncSynthVault::_claimRedeem` function which is used by user to claim the asset token.

```javascript
function _claimRedeem(
        address owner,
        address receiver
    )
        internal
        whenNotPaused
        returns (uint256 assets)
    {
        assets = previewClaimRedeem(owner);
        uint256 lastRequestId = lastRedeemRequestId[owner]; 
        uint256 shares = epochs[lastRequestId].redeemRequestBalance[owner]; 
        epochs[lastRequestId].redeemRequestBalance[owner] = 0; 
        _asset.safeTransferFrom(address(claimableSilo), address(this), assets);
@>      _asset.transfer(receiver, assets); //@audit not using safe transfer
        emit ClaimRedeem(lastRequestId, owner, receiver, assets, shares);
    }
```

## Impact
Tokens that don't actually perform the transfer and return false are still counted as a correct transfer and tokens that don't correctly implement the latest EIP20 spec will be unusable in the protocol as they revert the transaction because of the missing return value. This will lead to loss of token transfers.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L771

## Tool used
Manual Review

## Recommendation
Recommend using OpenZeppelin's SafeERC20 versions with the safeTransfer() functions that handle the return value check as well as non-standard-compliant tokens.

Duplicate of #126

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/103

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
