### ISSUE TITLE
rekxor - IERC20 transfer() returns a bool value that needs to be checked for successful transfer of tokens.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#124]
rekxor

medium

# IERC20 transfer() returns a bool value that needs to be checked for successful transfer of tokens.

## Summary
The ERC20.transfer() and ERC20.transferFrom() functions return a boolean value indicating success. This parameter needs to be checked for success. Some tokens do not revert if the transfer failed but return false instead.

## Vulnerability Detail
The return value of `.transfer()` on any ERC20 token needs to be checked to know if the `transfer` was successful and there were no silent failures.

## Impact
Tokens that don't actually perform the transfer and return false are still counted as a correct transfer. Furthermore, tokens that do not correctly implement the EIP20 standard, like USDT which does not return a success boolean, will revert.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L771

## Tool used
Manual Review

## Recommendation
We recommend using [OpenZeppelin’s SafeERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.1/contracts/token/ERC20/utils/SafeERC20.sol#L74) versions with the safeTransfer and safeTransferFrom functions that handle the return value check as well as non-standard-compliant tokens.

Duplicate of #126

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/103

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
