### ISSUE TITLE
Dudex_2004 - The deposit function does not check for the `maxMint` amount

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#127]
Dudex_2004

medium

# The deposit function does not check for the `maxMint` amount

Dudex_2004

medium 

## Summary
The deposit function does not check for the `maxMint` amount

## Vulnerability Detail
The `deposit` function has a check for `maxDeposit` and reverts if the deposit value is more than max(uint256). But, it does not check the shares to be less than `maxMint` amount and hence bypasses this check.

The `deposit` function is calling `previewDeposit` function which convert the assets into shares 
by `_convertToShares` function.

However, in the `_convertToShares` function the calculation  utilizes the mulDiv operation with parameters `totalSupply() + 1` and `totalAssets() + 1`.If the `totalSupply` is a very large number, the multiplication step might result in a very large number. This could potentially exceed the maximum number of shares that can be minted (maxMint).

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300C4-L317C6
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L449C5-L451C6
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L576C4-L585C6

## Tool used
solodit 

## Recommendation
include the `maxMint` check in the deposit function to prevent this problem.

**Comment by 0xHacker2684** [comment]
Escalate 
@Dudex_2004


This issue is talking about depositing into the vault, when vault is undercollateralized. In such case there is no check that amount of shares that will be minted is less than maxMint. This is a medium severity rather low. 

You could check the same issue found in previous contest - https://solodit.xyz/issues/m-04-the-deposit-function-does-not-check-for-the-maxmint-amount-code4rena-pooltogether-pooltogether-git

**Comment by sherlock-admin2** [comment]
> Escalate 
> @Dudex_2004
> 
> 
> This issue is talking about depositing into the vault, when vault is undercollateralized. In such case there is no check that amount of shares that will be minted is less than maxMint. This is a medium severity rather low. 
> 
> You could check the same issue found in previous contest - https://solodit.xyz/issues/m-04-the-deposit-function-does-not-check-for-the-maxmint-amount-code4rena-pooltogether-pooltogether-git
> 
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by 0xHacker2684** [comment]
This issue is talking about depositing into the vault, when vault is undercollateralized. In such case there is no check that amount of shares that will be minted is less than maxMint.

**Comment by 0xHacker2684** [comment]
Escalate please
