### ISSUE TITLE
rekxor - `_executePermit()` called on DAI token in `VaultZapper.sol` could fail

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#128]
rekxor

medium

# `_executePermit()` called on DAI token in `VaultZapper.sol` could fail

## Summary
Since DAI could be used in the zapper but not as a vault underlying. The `_executePermit()` called on DAI token in `VaultZapper.sol` doesn't function as intended.

## Vulnerability Detail
Dai's permit unfortunatelly doesn't follow the ERC2612 standard that we implement in ERC20Permit. The functions take different parameters 8 parameters instead of 7, and the signature is built differently.

## Impact
The function won't get executed for DAI token and can cause other functions that are depended on it to fail. Functions like ` zapAndDepositWithPermit()`, `zapAndRequestDepositWithPermit()` and `zapAndClaimAndRequestDepositWithPermit()` are dependent on the execution of this function.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/VaultZapper.sol#L367-L385

## Tool used
Manual Review

## Recommendation
Have a check if the `token` is DAI and correspondingly invoke it's Permit function if not go with the `ERC20Permit` function for rest of the tokens.

**Comment by rekxor** [comment]
Even, if the protocol face any issue, due to the forementioned case, sherlock's docs will have hierarchy? Could this be confirmed by the Sponsor, as "Since DAI could be used in the zapper but not as a vault underlying. " was mentioned by the Sponsor themselves
