### ISSUE TITLE
zzykxx - Vaults are not ERC4626 compliant

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#140]
zzykxx

medium

# Vaults are not ERC4626 compliant

## Vulnerability Detail
The vaults are not fully ERC4626 compliant
- The function [_claimDeposit](https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L742) should emit a `Deposit` event. (MUST be emitted when tokens are deposited into the Vault via the mint and deposit methods.)
- The function [_claimRedeem](https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L758) should emit a `Withdraw` event. (MUST be emitted when shares are withdrawn from the Vault in EIP-4626.redeem or EIP-4626.withdraw methods)

## Impact
Vault is not fully ERC4626 compliant.

## Tool used

Manual Review

## Recommendation
Emit the correct events when necessary.

**Comment by blablalf** [comment]
There is no deposit and no withdraw into these functions. This elements happen into `_settle` function which already emits the `Deposit` and `Withdraw` events.
- When there is a deposit via the mint and deposit methods, the `Deposit` event is emitted.
- When there is a withdraw via the redeem and withdraw methods, the `Withdraw` event is emitted.
