### ISSUE TITLE
miaowu - Only 1000USDC boostrap the vault cannot prevent inflation attacks

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#141]
miaowu

high

# Only 1000USDC boostrap the vault cannot prevent inflation attacks

## Summary
Only 1000USDC boostrap the vault cannot prevent inflation attacks

## Vulnerability Detail
The project side said in the document, "We will boostrap the vault to avoid inflation attack so please take this into consideration. For weth vault it would be 1 weth. For usdc vault it would be 1000 usdc." (https://audits. sherlock.xyz/contests/244)
However, this is not enough to prevent inflation attacks. According to the shares calculation formula, if the attacker `transfers` a larger amount of WETH/USDC after the contract is initialized (when the project completes the first deposit), making totalAssets much larger than totalSupply, the value of `assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding)` will be equal to 0. At this time, when normal users deposit assets, they will find that the shares will be 0 (generally, the amount deposited by normal users will be much smaller than the amount transferred by attackers for malicious purposes).

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300-L317

```solidity
 function deposit(
        uint256 assets,
        address receiver
    )
        public
        whenNotPaused
        returns (uint256)
    {
        uint256 maxAssets = maxDeposit(receiver);
        if (assets > maxAssets) {
            revert ERC4626ExceededMaxDeposit(receiver, assets, maxAssets);
        }

        uint256 sharesAmount = previewDeposit(assets);
        _deposit(_msgSender(), receiver, assets, sharesAmount);

        return sharesAmount;
    }
```
```solidity
function previewDeposit(uint256 assets) public view returns (uint256) {
        return _convertToShares(assets, Math.Rounding.Floor);
    }
```
```solidity
function _convertToShares(
        uint256 assets,
        Math.Rounding rounding
    )
        internal
        view
        returns (uint256)
    {
        return assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding);
    }
```

## Tool used
Manual Review

## Recommendation
While retaining the project's plan to boost the vault to avoid inflation attack, add the following measures:
1. Add virtual shares to increase the decimal places of shares and increase the attack cost, making it difficult for attackers to make totalAssets much larger than totalSupply.
2. Reverting if the share calculation returns zero. In this way, even if the attacker still chooses to forcefully attack the contract, the interests of normal users will not be harmed.

**Comment by blablalf** [comment]
Can you find one case where it's profitable for the attacker?
I don't see any demonstration, for me what you say is incorrect.
