### ISSUE TITLE
0xLogos - Exchange rate does not differ between deposit and redeem settlement

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#143]
0xLogos

high

# Exchange rate does not differ between deposit and redeem settlement

## Summary

Exchange rate is the same using `SnapshotForRedeem` and `SnapshotForDeposit`

## Vulnerability Detail

Each epoch has total assets & shares snapshot values meant to calculate settlement exchange rate for requested redeems and deposits differently:
```solidity
struct EpochData {
    uint256 totalSupplySnapshotForRedeem;
    uint256 totalAssetsSnapshotForRedeem;
    uint256 totalSupplySnapshotForDeposit;
    uint256 totalAssetsSnapshotForDeposit;
    mapping(address => uint256) depositRequestBalance;
    mapping(address => uint256) redeemRequestBalance;
}
```

But exchange rate end ups the same.

Here is [code](https://github.com/sherlock-audit/2024-03-amphor/blob/6c797025ffe296e04607abf74400ff2bb36a7de3/asynchronous-vault/src/AsyncSynthVault.sol#L649-L664) for calculation:
```solidity
uint256 totalAssetsSnapshotForDeposit = _lastSavedBalance + 1;
uint256 totalSupplySnapshotForDeposit = totalSupply + 1;

uint256 sharesToMint = pendingDeposit.mulDiv(
    totalSupply + 1, _lastSavedBalance + 1, Math.Rounding.Floor
);
uint256 totalAssetsSnapshotForRedeem =_lastSavedBalance + pendingDeposit + 1;
uint256 totalSupplySnapshotForRedeem = totalSupply + sharesToMint + 1;

---

let _lastSavedBalance = b, totalSupply = s, pendingDeposit = p, ignoring "+1"
deposit exchange rate = b / s
redeem exchange rate = (b + p) / (s + p*s/b)

b / s == (b + p) / (s + p*s/b)
(b / s) * (s + p*s/b) == b + p
b + p == b + p <-- always true
```

## Impact

Exchange rate does not differ between deposit and redeem settlement. Actually I don't know if it's matters and mb this is just gas issue (or my blunder ;). But I'm not sure since there's special variables and calculations for each case. 

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/6c797025ffe296e04607abf74400ff2bb36a7de3/asynchronous-vault/src/AsyncSynthVault.sol#L653-L654

https://github.com/sherlock-audit/2024-03-amphor/blob/6c797025ffe296e04607abf74400ff2bb36a7de3/asynchronous-vault/src/AsyncSynthVault.sol#L662-L664

## Tool used

Manual Review

## Recommendation

If it's not intended behavior let's discuss solution.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/113

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
