### ISSUE TITLE
whitehair0330 - A miner can conduct a donation attack.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#24]
whitehair0330

high

# A miner can conduct a donation attack.

## Summary

At the first deposit, a miner can execute a donation attack through front running.

## Vulnerability Detail

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300-L317

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L449-L451

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L487-L507

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L576-L585

```javascript
    function deposit(
        uint256 assets,
        address receiver
    )
        public
        whenNotPaused
        returns (uint256)
    {
        uint256 maxAssets = maxDeposit(receiver);
        if (assets > maxAssets) {
            revert ERC4626ExceededMaxDeposit(receiver, assets, maxAssets);
        }

        uint256 sharesAmount = previewDeposit(assets);
        _deposit(_msgSender(), receiver, assets, sharesAmount);

        return sharesAmount;
    }

    function previewDeposit(uint256 assets) public view returns (uint256) {
        return _convertToShares(assets, Math.Rounding.Floor);
    }

    function _deposit(
        address caller,
        address receiver,
        uint256 assets,
        uint256 shares
    )
        internal
    {
        //...
        _asset.safeTransferFrom(caller, address(this), assets);
        _mint(receiver, shares);
        emit Deposit(caller, receiver, assets, shares);
    }

    function _convertToShares(
        uint256 assets,
        Math.Rounding rounding
    )
        internal
        view
        returns (uint256)
    {
        return assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding);
    }
```

Let's consider a simplified scenario:

1. There are 3 deposit transactions in the pool with amounts of $100, $90, and $80 respectively.
2. Bob, the malicious miner, initiates a deposit transaction of $1.
3. Bob then transfers $199 to the vault.
4. Bob places his 2 transactions at the beginning of the block, along with 3 other transactions.

In this sequence, Bob's initial transaction results in `totalSupply() = 1` and `totalAssets() = 1`, granting Bob 1 share.
Subsequently, Bob's second transaction leads to `totalSupply() = 1` and `totalAssets() = 200`.
This adjustment affects the exchange rate to become (1+1)/(200+1) = 2/201.
As a result, the other three individuals receive no shares, resulting in `totalSupply() = 1` and `totalAssets() = 200+100+90+80`.
Consequently, the new exchange rate is (1+1)/(470) = 1/235.
Therefore, Bob can claim $235 with his 1 share, resulting in Bob acquiring an additional $35.

## Impact

A malicious miner can acquire unfair assets through the donation attack.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L300-L317

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L449-L451

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L487-L507

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L576-L585

## Tool used

Manual Review

## Recommendation

I'm not sure, but I think a small portion of the shares from the first deposit should be sent to `address(1)`.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/103

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
