### ISSUE TITLE
whitehair0330 - Incorrect event emission of `AsyncSynthVault.settle()`.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#27]
whitehair0330

medium

# Incorrect event emission of `AsyncSynthVault.settle()`.

## Summary

During each settlement, the second parameter of the `EpochStart` event is consistently 0 instead of the actual value.

## Vulnerability Detail

At [L351](https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L351) of `AsyncSynthVault.settle()`, the local variable `lastSavedBalance` is reset to 0.

```javascript
    function settle(uint256 newSavedBalance) external {
        (uint256 lastSavedBalance, uint256 totalSupply) =
            _settle(newSavedBalance);
351     lastSavedBalance = 0;
        emit EpochStart(block.timestamp, lastSavedBalance, totalSupply);
    }
```

## Impact

Anyone receives incorrect information regarding the epochs.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L348-L353

## Tool used

Manual Review

## Recommendation

`AsyncSynthVault.settle()` should be fixed as follows.

```diff
    function settle(uint256 newSavedBalance) external {
       (uint256 lastSavedBalance, uint256 totalSupply) =
            _settle(newSavedBalance);
-       lastSavedBalance = 0;
        emit EpochStart(block.timestamp, lastSavedBalance, totalSupply);
    }
```

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/106

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
