### ISSUE TITLE
bareli - use of '_disableInitializers'

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#41]
bareli

medium

# use of '_disableInitializers'

## Summary
use of '_disableInitializers'  so that initialize cannot happen again.
## Vulnerability Detail
 constructor() {
        _disableInitializers();
    }
## Impact
Any one can call SyncSynthVault contract and  initialize the contract.
## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L160
## Tool used

Manual Review

## Recommendation
use  _disableInitializers(); in constructor.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/commit/e2f030244f43a651031598bd2051de029628154e

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
