### ISSUE TITLE
kennedy1030 - Donation attack can be done by miners.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#49]
kennedy1030

high

# Donation attack can be done by miners.

## Summary

If there are some depositing transactions in pool and they satisfies some conditions, a miner vault can carry out a sandwich attack in a empty vault.

## Vulnerability Detail

Suppose that there are three depositing transactions in pool. Each of them is going to deposit 100 assets into the vault.
Let them be utx1, utx2 and utx3. 
Then, the miner makes three transactions and they are mtx1, mtx2 and mtx3.
    mtx1: deposits 1 asset to vault and takes 1 share.
    mtx2: donate 199 assets to vault.
    mtx3: redeem 1 share.
Next, the miner constructs put these transactions in block by the following order .
    ... mtx1, mtx2, utx1, utx2, utx3, mtx3 ...

In utx1, utx2 and utx3, each user takes `100*(1+1)/(200+1) = 0` share from vault. (L584 in the following code.)
This leads to `totalSupply() == 1` and `totalAssets() == 500`.
By redeeming 1 share in mtx3, the miner can take `1*501/2 = 250` assets and earn `250-200 = 50` assets.

Generally, a donation attack is available when the max value of depositing assets in the transaction pool is smaller than the sum of remaining depositing assets.

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L584

```javascript
        function _convertToShares(
            uint256 assets,
            Math.Rounding rounding
        )
            internal
            view
            returns (uint256)
        {
584         return assets.mulDiv(totalSupply() + 1, totalAssets() + 1, rounding);
        }
```

## Impact

A miner takes some assets from the depositors and they lose their funds without any shares given.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/SyncSynthVault.sol#L584

## Tool used

Manual Review

## Recommendation

Some shares of the first depositor have to be burnt.

**Comment by kennedy1030** [comment]
Escalate

medium

The inflation attack in #49 is a valid one, not a dup of 129. The attacker can take some profit. I hope #49 to be reconsidered again.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> medium
> 
> The inflation attack in #49 is a valid one, not a dup of 129. The attacker can take some profit. I hope #49 to be reconsidered again.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
