### ISSUE TITLE
Afriaudit - `_createRedeemRequest` and `_createDepositRequest` did not include the `assets` parameter to the `onERC7540DepositReceived` and `onERC7540RedeemReceived` callback thus EIP7540 non-compliant

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#51]
Afriaudit

medium

# `_createRedeemRequest` and `_createDepositRequest` did not include the `assets` parameter to the `onERC7540DepositReceived` and `onERC7540RedeemReceived` callback thus EIP7540 non-compliant

## Summary
According to the EIP7540 standard the `onERC7540DepositReceived` and `onERC7540RedeemReceived` function takes in 5 parameters which are; `operator's address` ,`owner's address`, `requestID`, `asset` and `data` however only four parameters where passed in the `onERC7540DepositReceived` and `onERC7540RedeemReceived` callback to the receiver omitting the `assets` parameter which is a non-compliance to the  EIP7540 standard

## Vulnerability Detail
https://eips.ethereum.org/EIPS/eip-7540
This is a Link to the EIP7540 documentation
![Screenshot (162)](https://github.com/sherlock-audit/2024-03-amphor-Afriaudit/assets/161083216/6aff58a5-2e04-4754-8bb2-0c8d562cef52)
![Screenshot (163)](https://github.com/sherlock-audit/2024-03-amphor-Afriaudit/assets/161083216/4a2d1c53-5527-4b72-a567-13a12cadbdf0)
Attached is a screenshot showing the appropriate implementation according to the EIP7540 standard.
This would mean current Implementation is not calling the hook of the reciever with the parameters as stated by the EIP7540 thus not compliant with the IERC7540 standard, which could lead to interoperability issues with other contracts which adheres to the standard.
```solidity
 function _createDepositRequest(
        uint256 assets,
        address receiver,
        address owner,
        bytes memory data
    )
        internal
    {
        epochs[epochId].depositRequestBalance[receiver] += assets;
        if (lastDepositRequestId[receiver] != epochId) {
            lastDepositRequestId[receiver] = epochId;
        }

        if (
            data.length > 0
                && ERC7540Receiver(receiver).onERC7540DepositReceived(
                    _msgSender(), owner, epochId, data
                ) != ERC7540Receiver.onERC7540DepositReceived.selector
        ) revert ReceiverFailed();

        emit DepositRequest(receiver, owner, epochId, _msgSender(), assets);
    }
```
The `_createDepositRequest` above when called with ` bytes memory data` will trigger a callback to reciever with this check
` if (
            data.length > 0
                && ERC7540Receiver(receiver).onERC7540DepositReceived(
                    _msgSender(), owner, epochId, data
                ) != ERC7540Receiver.onERC7540DepositReceived.selector
        ) revert ReceiverFailed();`
however `ERC7540Receiver(receiver).onERC7540DepositReceived(
                    _msgSender(), owner, epochId, data
                ) `
this section is calling on just four parameters instead of 5 omitting `assets` as stated by EIP and same applies to the `_createRedeemRequest` function
## Impact
Could result to reversion of Transactions If the receiver contract expects the `assets` parameter and it's not provided. This will eventually result to a DOS hindering users from requesting deposits and requesting redeems.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L734

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L713

## Tool used

Manual Review

## Recommendation
Follow the EIP EIP7540 standard
```solidity
if (
            data.length > 0
                && ERC7540Receiver(receiver).onERC7540DepositReceived(
   +                 _msgSender(), owner, epochId, assets, data
                ) != ERC7540Receiver.onERC7540DepositReceived.selector
        ) revert ReceiverFailed();
```

```solidity
if (
            data.length > 0
                && ERC7540Receiver(receiver).onERC7540RedeemReceived(
      +              _msgSender(), owner, epochId, assets, data
                ) != ERC7540Receiver.onERC7540RedeemReceived.selector
        ) revert ReceiverFailed();
```

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/113

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
