### ISSUE TITLE
bigbick123456789000 - Lack of Safe Token Transfer Handling in `_claimRedeem` Function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-amphor-judging#55]
bigbick123456789000

medium

# Lack of Safe Token Transfer Handling in `_claimRedeem` Function

## Summary
The `_claimRedeem` function within the smart contract lacks proper handling for token transfers, potentially leading to silent failures and affecting token accounting within the contract.
## Vulnerability Detail
The `_claimRedeem` function is responsible for transferring assets from a claimable silo to a specified receiver address. However, it doesn't utilize safe transfer functions such as OpenZeppelin's `safeTransfer()` . Without these safety measures, the function may encounter issues such as reentrancy attacks or failing transfers due to non-compliant ERC20 tokens.

Here's a breakdown of the vulnerability in the code:

The function transfers assets using the `_asset` contract's `transfer()` without checking for the success of the transfers.
If a transfer fails due to reasons such as insufficient allowance or invalid token contract behaviour, the function will not revert, leading to silent failures.
Silent failures can result in discrepancies in token accounting within the contract, potentially causing loss of funds or incorrect balances for users.
## Impact
The lack of proper token transfer handling in the `_claimRedeem` function can lead to silent failures of transfers and affect token accounting within the contract. This could result in loss of funds or incorrect balance calculations for users, ultimately undermining the integrity and reliability of the contract.
## Code Snippet
[AsyncSynthVault.sol#L758-L773](https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L758-L773)
## Tool used

Manual Review

## Recommendation
 it's crucial to implement safe token transfer mechanisms within the _claimRedeem function. Use OpenZeppelin's `safeTransfer()` function

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/103

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
