### ISSUE TITLE
MrMorningstar - H-1: Unchecked Transfer "AsyncSynthVault::_claimRedeem"

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#56]
MrMorningstar

high

# H-1: Unchecked Transfer "AsyncSynthVault::_claimRedeem"

---
MrMorningstar

High

---
# H-1: Unchecked Transfer `AsyncSynthVault::_claimRedeem`

## Summary
The return value of an external transfer call is not checked.
## Vulnerability Detail
Function does not check return value of the transfer call.
## Impact
 A contract calls an external contract to perform a critical operation and assumes that the call will always succeed. However, if the external contract encounters an fail, revert, gas limit or malicious behavior, the calling contract may proceed with unintended actions.
## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L771
## Tool used

Manual Review

## Recommendation
Ensure that the transfer return value is checked and follow CEI.
```diff
+ (bool sent, bytes memory data) = receiver.call{value: assets}("");
+ require(sent, "Failed to send assets");
- _asset.transfer(receiver, assets);
```

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/103

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
