### ISSUE TITLE
Afriaudit - `ERC7540Receiver.onERC7540RedeemReceived` and `ERC7540Receiver.onERC7540DepositReceived` does not Follow EIP7540 specification

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#59]
Afriaudit

medium

# `ERC7540Receiver.onERC7540RedeemReceived` and `ERC7540Receiver.onERC7540DepositReceived` does not Follow EIP7540 specification

## Summary
The implementation of `onERC7540RedeemReceived` and  `onERC7540DepositReceived` does not follow the EIP7540 standard which states the function takes in 5 parameters which are; `operator's address` ,`owner's address`,` requestID`,`asset` and `data` however only four parameters where passed in the `ERC7540Receiver.onERC7540RedeemReceived` and `ERC7540Receiver.onERC7540DepositReceived` omitting the `assets` parameter which is a non-compliance to the EIP7540 standard
## Vulnerability Detail
![Screenshot (162)](https://github.com/sherlock-audit/2024-03-amphor-Afriaudit/assets/161083216/ac39414f-ad74-4c31-b740-4704a84dfe8a)

![Screenshot (163)](https://github.com/sherlock-audit/2024-03-amphor-Afriaudit/assets/161083216/2f01d1ab-9201-43ed-8c93-54464e08b9be)

The above photo is the implementation according to the EIP7540 as stated in the documentation here https://eips.ethereum.org/EIPS/eip-7540. This would mean the function selector will be different coz altering any parameter within a function declaration, even if the other parameters remain unchanged, leads to a different function signature.
A change in the function selector will affect interoperability with other smart-contact that expects implementation of the EIP7540 standard.

## Impact
This could lead to interoperability issues with other contracts expecting the standard's adherence.

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/interfaces/ERC7540Receiver.sol#L5

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/interfaces/ERC7540Receiver.sol#L14

## Tool used

Manual Review

## Recommendation
Follow EIP7540 standards
```solidity

interface ERC7540Receiver {
    function onERC7540DepositReceived(
        address operator,
        address owner,
        uint256 requestId,
 +     uint256 assets,
        bytes memory data
    )
        external
        returns (bytes4);

    function onERC7540RedeemReceived(
        address operator,
        address owner,
        uint256 requestId,
 +     uint256 assets,
        bytes memory data
    )
        external
        returns (bytes4);
}

```

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/AmphorProtocol/asynchronous-vault/pull/113

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
