### ISSUE TITLE
Afriaudit - The `_claimRedeem` function carries out asset transfers to users in an unsafe manner.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#62]
Afriaudit

medium

# The `_claimRedeem` function carries out asset transfers to users in an unsafe manner.

## Summary
The  `_claimRedeem` firstly implements a wrong design of sending assets to vault before sending to the reciever. In addition to that It does this transfer from vault to user in an unsafe manner `_asset.transfer(receiver, assets)` without checking return values. Protocol even uses usdt which return no values on failure thus can fail silently.

## Vulnerability Detail
```solidity
function _claimRedeem(
        address owner,
        address receiver
    )
        internal
        whenNotPaused
        returns (uint256 assets)
    {
        assets = previewClaimRedeem(owner);
        uint256 lastRequestId = lastRedeemRequestId[owner];
        uint256 shares = epochs[lastRequestId].redeemRequestBalance[owner];
        epochs[lastRequestId].redeemRequestBalance[owner] = 0;
        _asset.safeTransferFrom(address(claimableSilo), address(this), assets);
 >>    _asset.transfer(receiver, assets);
        emit ClaimRedeem(lastRequestId, owner, receiver, assets, shares);
    }

```
This function unnecessarily sends token to the contract instead of sending directly to users with the `_asset.safeTransferFrom` above
and then does an unsafe transfer to receiver `_asset.transfer(receiver, assets);`

## Impact
risk of uncaught failed transfer and risk of loss of funds to users as state will be updated with no actual transfer made

## Code Snippet
https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/AsyncSynthVault.sol#L771

## Tool used

Manual Review

## Recommendation
send asset directly to reciever with the transfer from 
`+  _asset.safeTransferFrom(address(claimableSilo), reciever, assets);`

**Comment by WangSecurity** [comment]
Escalate

In the summary the watson indeed mentions USDT, therefore, it should be valid and a duplicate of #126

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> In the summary the watson indeed mentions USDT, therefore, it should be valid and a duplicate of #126 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Planning to accept escalation and duplicate with #126

**Comment by Evert0x** [comment]
One a second look, this issue notes that the USDT tranfer can fail silently because it has no return value, it;s not the case. There is no silent failure in this issue. The issue is a revert in the whole call, causing a DoS.

For that reason, I think this issue fails to identify the core issue. @WangSecurity

**Comment by Afriauditor** [comment]
Sigh🤦... Intent is to highlight both unsafe transfer and also underscore usdt not returning a bool causing it to fail together In my summary together. @Evert0x

**Comment by Evert0x** [comment]
@Afriauditor your issue describes that the transfer "fails silently" which would mean that the transaction is successful but without any token transfer. 

In reality the transfer doesn't fail silently as described in #126

**Comment by WangSecurity** [comment]
At this point, I will agree with @Evert0x Even tho the report mentions USDT, it doesn't say what will happen exactly, i.e. the transfer for it will always fail.

**Comment by Afriauditor** [comment]
@Evert0x went through the report again can see why u say it does not Identify the core issue. My only reason for underscoring the usdt not returning a bool is to highlight it failing or reverting even after stating the unsafe transfer. I can see why u would see otherwise from how it was phrased. And I will happily accept whatever the outcome of this escalation is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [WangSecurity](https://github.com/sherlock-audit/2024-03-amphor-judging/issues/62/#issuecomment-2025075372): rejected
