### ISSUE TITLE
fugazzi - Strict check could cripple functionality in Zapper

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-amphor-judging#74]
fugazzi

medium

# Strict check could cripple functionality in Zapper

## Summary

The VaultZapper contract enforces that no leftovers are present after the input token is _zapped_. This could damage compatibility with routers that execute trades on exact outputs, rather than an exact input, as the input amount may not be covered in full.

## Vulnerability Detail

Before depositing assets to the vault, the VaultZapper contract executes a _zap_ in which the input token is swapped using a whitelisted router. The implementation is given by `_zapIn()`:

```solidity
function _zapIn(
    IERC20 tokenIn,
    address router,
    uint256 amount,
    bytes calldata data
)
    internal
{
    uint256 expectedBalance; // of tokenIn (currently)

    if (msg.value == 0) {
        expectedBalance = tokenIn.balanceOf(address(this));
        _transferTokenInAndApprove(router, tokenIn, amount);
    } else {
        expectedBalance = address(this).balance - msg.value;
    }

    _executeZap(router, data); // zap

    uint256 balanceAfterZap = msg.value == 0
        ? tokenIn.balanceOf(address(this))
        : address(this).balance;

    if (balanceAfterZap > expectedBalance) {
        // Our balance is higher than expected, we shouldn't have received
        // any token
        revert InconsistantSwapData({
            expectedTokenInBalance: expectedBalance,
            actualTokenInBalance: balanceAfterZap
        });
    }
}
```

Note that function checks that there are no leftovers of the input token (or ETH if `msg.value > 0`). It records the `expectedBalance` before pulling the tokens, and after executing the zap it checks this value against `balanceAfterZap`, reverting if there is a positive difference.

This will conflict with functions commonly present in routers that operate on exact output amounts. In this case, the user provides a certain amount of tokens (or ETH) with some margin to account for slippage, expecting a fixed amount of output tokens. This margin will likely cause a minimal leftover that will result in a revert, crippling the zapper functionality.

A common example of such a router is the UniswapV2Router (https://github.com/Uniswap/v2-periphery/blob/master/contracts/UniswapV2Router02.sol). The `swapTokensForExactTokens()` function takes a max amount in and will pull tokens as long as the calculated amount is below that max. Another example is `swapETHForExactTokens()`, which will refund the user the excess of ETH sent.

## Impact

The zapper implementation will be incompatible with certain functions that are typically found in routers.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/VaultZapper.sol#L150-L157

## Tool used

Manual Review

## Recommendation

Instead of checking that there are no leftovers after executing the zap, avoid the revert and refund the difference to the user.

**Comment by realfugazzi** [comment]
> 1 comment(s) were left on this issue during the judging contest.
> 
> **WangAudit** commented:
> 
> > owners are trusted; therefore; has to assume they will provide the correct router; but good catch 很棒！

hey @WangSecurity , don't think this has to do with trusting or not the owners. This is an issue in the design of the zapper that won't allow integrations with common routers present in the ecosystem. I'm open to discuss the validity or severity but please let's review the reason.
