### ISSUE TITLE
kennedy1030 - Incorrect allowance validation in `VaultZapper._transferTokenInAndApprove()`.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-amphor-judging#81]
kennedy1030

medium

# Incorrect allowance validation in `VaultZapper._transferTokenInAndApprove()`.

## Summary

In `VaultZapper._transferTokenInAndApprove()`, the allowance for `address(this)` should be checked, but the allowance for `_msgSender()` is checked.

## Vulnerability Detail

In [L168] of the following, the allowance for `address(this)` should be checked, but the allowance for `_msgSender()` is checked.

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/VaultZapper.sol#L168

```javascript
    function _transferTokenInAndApprove(
        address router,
        IERC20 tokenIn,
        uint256 amount
    )
        internal
    {
        tokenIn.safeTransferFrom(_msgSender(), address(this), amount);
168     if (tokenIn.allowance(_msgSender(), router) < amount) {
            tokenIn.forceApprove(router, amount);
        }
    }
```

`_transferTokenInAndApprove` is called in `_zapIn()`, which is the main function of _transferTokenInAndApprove. 
Furthermore, this may lead to modifications of the allowance which was properly configured already.

## Impact

The function, `_zapIn()` which is the main function of `VaultZapper` could be reverted unreasonanbly, it may lead to partial DOS of `VaultZapper`.

## Code Snippet

https://github.com/sherlock-audit/2024-03-amphor/blob/main/asynchronous-vault/src/VaultZapper.sol#L168

## Tool used

Manual Review

## Recommendation

```diff
    function _transferTokenInAndApprove(
        address router,
        IERC20 tokenIn,
        uint256 amount
    )
        internal
    {
        tokenIn.safeTransferFrom(_msgSender(), address(this), amount);
-       if (tokenIn.allowance(_msgSender(), router) < amount) {
+       if (tokenIn.allowance(address(this), router) < amount) {
            tokenIn.forceApprove(router, amount);
        }
    }
```

**Comment by kennedy1030** [comment]
##Escalate
This issue is very clear to understand. I thought that recommendation is enough to explain about this issue.
